# Generated by Django 5.2.6 on 2025-11-18 23:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_alter_conversation_options_conversation_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('rating', models.FloatField(default=0.0)),
                ('user_ratings_total', models.IntegerField(default=0)),
                ('types', models.JSONField(default=list)),
                ('photo_url', models.URLField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('price_level', models.IntegerField(blank=True, help_text='1-4 price range', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rating', '-user_ratings_total'],
            },
        ),
        migrations.CreateModel(
            name='FlightSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=3)),
                ('destination', models.CharField(max_length=3)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('cabin_class', models.CharField(default='ECONOMY', max_length=50)),
                ('num_passengers', models.IntegerField(default=1)),
                ('results', models.JSONField(default=list, help_text='Cached flight results')),
                ('result_count', models.IntegerField(default=0)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('searched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(help_text='When this cache expires')),
            ],
            options={
                'ordering': ['-searched_at'],
                'indexes': [models.Index(fields=['origin', 'destination', 'departure_date'], name='agent_fligh_origin_2d4972_idx'), models.Index(fields=['expires_at'], name='agent_fligh_expires_4ad248_idx')],
            },
        ),
        migrations.CreateModel(
            name='FlightBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Session from conversation', max_length=255)),
                ('order_id', models.CharField(help_text='Mistifly OrderID', max_length=100, unique=True)),
                ('pnr', models.CharField(blank=True, help_text='Passenger Name Record', max_length=50)),
                ('booking_reference', models.CharField(blank=True, max_length=100)),
                ('airline_pnr', models.CharField(blank=True, help_text='Airline-specific PNR', max_length=50)),
                ('origin', models.CharField(help_text='Origin airport IATA code', max_length=3)),
                ('destination', models.CharField(help_text='Destination airport IATA code', max_length=3)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('airline_code', models.CharField(blank=True, max_length=3)),
                ('airline_name', models.CharField(blank=True, max_length=200)),
                ('flight_number', models.CharField(blank=True, max_length=20)),
                ('cabin_class', models.CharField(default='ECONOMY', max_length=50)),
                ('passengers', models.JSONField(default=list, help_text='List of passenger details')),
                ('num_passengers', models.IntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=50)),
                ('ticket_numbers', models.JSONField(blank=True, default=list, help_text='E-ticket numbers')),
                ('ticketed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('ticketed', 'Ticketed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('raw_itinerary', models.JSONField(default=dict, help_text='Raw Mistifly itinerary data')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_bookings', to='agent.conversation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order_id'], name='agent_fligh_order_i_03e22f_idx'), models.Index(fields=['pnr'], name='agent_fligh_pnr_8906c0_idx'), models.Index(fields=['session_id'], name='agent_fligh_session_38d302_idx'), models.Index(fields=['status'], name='agent_fligh_status_fd1dfc_idx')],
            },
        ),
    ]
