# Generated by Django 5.2.6 on 2025-12-17 09:43

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_place_flightsearch_flightbooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monei_payment_id', models.CharField(help_text='Monei payment ID', max_length=255, unique=True)),
                ('monei_transaction_id', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('webhook_data', models.JSONField(default=dict, help_text='Raw webhook payload')),
                ('webhook_received_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('webhook_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(help_text='payment.succeeded, payment.failed, etc.', max_length=50)),
                ('monei_event_id', models.CharField(blank=True, help_text='Monei event ID for idempotency', max_length=255)),
                ('payload', models.JSONField(help_text='Full webhook payload')),
                ('signature', models.TextField(help_text='Webhook signature for verification')),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='flightbooking',
            name='agent_fligh_order_i_03e22f_idx',
        ),
        migrations.RemoveIndex(
            model_name='flightbooking',
            name='agent_fligh_status_fd1dfc_idx',
        ),
        migrations.RenameField(
            model_name='flightbooking',
            old_name='order_id',
            new_name='mistifly_order_id',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='id',
        ),
        migrations.RemoveField(
            model_name='flightbooking',
            name='status',
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='booking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 17, 10, 13, 58, 818857, tzinfo=datetime.timezone.utc), help_text='Booking expires if not paid by this time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='payment_intent_id',
            field=models.CharField(blank=True, help_text='Monei payment ID', max_length=255),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='payment_method',
            field=models.CharField(blank=True, help_text='card, bank_transfer, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PROCESSING', 'Payment Processing'), ('PAID', 'Payment Successful'), ('FAILED', 'Payment Failed'), ('EXPIRED', 'Booking Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='payment_url',
            field=models.URLField(blank=True, help_text='Monei checkout URL'),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='refund_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='refund_status',
            field=models.CharField(choices=[('NOT_REFUNDED', 'Not Refunded'), ('REQUESTED', 'Refund Requested'), ('PROCESSING', 'Processing Refund'), ('REFUNDED', 'Refunded'), ('REJECTED', 'Refund Rejected')], default='NOT_REFUNDED', max_length=20),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='ticket_status',
            field=models.CharField(choices=[('NOT_ISSUED', 'Not Issued'), ('ISSUING', 'Being Issued'), ('ISSUED', 'Ticket Issued'), ('FAILED', 'Issuance Failed')], default='NOT_ISSUED', max_length=20),
        ),
        migrations.AddField(
            model_name='flightbooking',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Monei transaction reference', max_length=255),
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='airline_pnr',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='flightsearch',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flightsearch',
            name='results',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='place',
            name='price_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='flightbooking',
            index=models.Index(fields=['mistifly_order_id'], name='agent_fligh_mistifl_2cec3b_idx'),
        ),
        migrations.AddIndex(
            model_name='flightbooking',
            index=models.Index(fields=['payment_status'], name='agent_fligh_payment_e621af_idx'),
        ),
        migrations.AddIndex(
            model_name='flightbooking',
            index=models.Index(fields=['payment_intent_id'], name='agent_fligh_payment_b276ab_idx'),
        ),
        migrations.AddIndex(
            model_name='flightbooking',
            index=models.Index(fields=['expires_at'], name='agent_fligh_expires_9da174_idx'),
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='agent.flightbooking'),
        ),
        migrations.AddField(
            model_name='webhooklog',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='agent.flightbooking'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['monei_payment_id'], name='agent_payme_monei_p_019019_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='agent_payme_status_69dc03_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['monei_event_id'], name='agent_webho_monei_e_40048c_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['processed'], name='agent_webho_process_1aa670_idx'),
        ),
    ]
